//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbinteg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Netmetering
    {
        public int Id { get; set; }
        public string Month { get; set; }
        public Nullable<double> MonthlyConsumption { get; set; }
        public Nullable<double> NetConsumption { get; set; }
        public Nullable<decimal> MonthlyBill { get; set; }
        public Nullable<decimal> BillAfterPlan { get; set; }
        public Nullable<decimal> Savings { get; set; }
        public Nullable<int> payback { get; set; }
    }
}
