//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbinteg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public int Id { get; set; }
        public string KW { get; set; }
        public string Area { get; set; }
        public Nullable<int> No_of_panels { get; set; }
        public Nullable<int> Rs_Watt { get; set; }
        public Nullable<int> Cost_of_Solar_Panel { get; set; }
        public Nullable<int> Cost_of_Inverter { get; set; }
    }
}
