//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbinteg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public Nullable<int> ContactNo { get; set; }
        public string Address { get; set; }
    }
}
